# Code Generated by Sidekick is for learning and experimentation purposes only.
import datetime
import logging
import os
import requests
import json
import azure.functions as func
from msal import ConfidentialClientApplication

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')

    # Get environment variables
    tenant_id = os.getenv('tenant-id')
    client_id = os.getenv('client-id')
    client_secret = os.getenv('client-secret')
    logic_app_url = os.getenv('logic-app-url')

    # Initialize the MSAL client
    app = ConfidentialClientApplication(
        client_id,
        authority=f"https://login.microsoftonline.com/{tenant_id}",
        client_credential=client_secret
    )

    # Acquire a token
    result = app.acquire_token_for_client(scopes=["https://graph.microsoft.com/.default"])

    if "access_token" in result:
        access_token = result["access_token"]
        headers = {
            'Authorization': f'Bearer {access_token}',
            'Content-Type': 'application/json'
        }

        # Get users from Microsoft Graph
        users_response = requests.get('https://graph.microsoft.com/v1.0/users', headers=headers)
        users = users_response.json().get('value', [])

        for user in users:
            last_password_change_date = user.get('lastPasswordChangeDateTime')
            if last_password_change_date:
                last_password_change_date = datetime.datetime.strptime(last_password_change_date, '%Y-%m-%dT%H:%M:%SZ')
                password_expiry_date = last_password_change_date + datetime.timedelta(days=90)  # Assuming 90 days password policy

                if password_expiry_date <= datetime.datetime.utcnow() + datetime.timedelta(days=14):
                    trigger_logic_app(user, logic_app_url)

        return func.HttpResponse("Function executed successfully.", status_code=200)
    else:
        return func.HttpResponse("Failed to acquire token.", status_code=500)

def trigger_logic_app(user, logic_app_url):
    payload = {
        'userPrincipalName': user['userPrincipalName'],
        'expiryDate': (datetime.datetime.strptime(user['lastPasswordChangeDateTime'], '%Y-%m-%dT%H:%M:%SZ') + datetime.timedelta(days=90)).isoformat()
    }
    headers = {'Content-Type': 'application/json'}
    response = requests.post(logic_app_url, data=json.dumps(payload), headers=headers)
    logging.info(f"Logic App triggered with response: {response.status_code}")




















# import azure.functions as func
# import datetime
# import json
# import logging

# app = func.FunctionApp()

# @app.route(route="CheckPasswordExpiryFunction", auth_level=func.AuthLevel.ANONYMOUS)
# def CheckPasswordExpiryFunction(req: func.HttpRequest) -> func.HttpResponse:
#     logging.info('Python HTTP trigger function processed a request.')

#     name = req.params.get('name')
#     if not name:
#         try:
#             req_body = req.get_json()
#         except ValueError:
#             pass
#         else:
#             name = req_body.get('name')

#     if name:
#         return func.HttpResponse(f"Hello, {name}. This HTTP triggered function executed successfully.")
#     else:
#         return func.HttpResponse(
#              "This HTTP triggered function executed successfully. Pass a name in the query string or in the request body for a personalized response.",
#              status_code=200
#         )